version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
        - "5432:5444"
  app:
      build:
        context: ..
        dockerfile: ./build/package/Dockerfile
      command: ["make", "run"]
      ports:
        - "8080:8080"