version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
        - "127.0.0.1:5432:5432"
  app:
      build:
        context: ..
        dockerfile: ./build/package/Dockerfile
      command: ["make", "run"]
      ports:
        - "3009:3009"