language: go
go:
- master
sudo: required
notifications:
  email:
    onfailure: change
    onsuccess: change
services:
- docker
- postgresql
addons:
  ssh_known_hosts:
    - maxkrasnov.ru
branches:
  only:
  - master
script:
- echo 'pass'
deploy:
  provider: script
  skip_cleanup: true
  script:
  - ssh $TRAVIS_USER@maxkrasnov.ru 'rm -rf ru.maxkrasnov.api&&git
    clone https://github.com/maxkrasnov/ru.maxkrasnov.api.git&&cd ru.maxkrasnov.api&&make
    deploy'
  on:
    branch: master
before_deploy:
- openssl aes-256-cbc -K $encrypted_c64829bbe366_key -iv $encrypted_c64829bbe366_iv
  -in deploy.enc -out deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy
- ssh-add deploy
