language: go
go:
  - master
sudo: required
notifications:
  email:
    onfailure: change
    onsuccess: change
addons:
  ssh_known_hosts:
    - maxkrasnov.ru
  apt:
    packages:
      - sshpass
branches:
  only:
    - master
script:
  - make deploy
deploy:
  provider: script
  skip_cleanup: true
  script:
    - ssh $TRAVIS_USER@maxkrasnov.ru 'rm -rf ru.maxkrasnov.api&&git clone https://github.com/maxkrasnov/ru.maxkrasnov.api.git&&cd ru.maxkrasnov.api&&make deploy'
  on:
    branch: master
before_deploy:
  - openssl aes-256-cbc -K $encrypted_a95c2b96b935_key -iv $encrypted_a95c2b96b935_iv -in /build/ci/deploy.enc -out deploy -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy
  - ssh-add deploy